/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

/**
 *
 * @author Iqbal Albana
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public static int saldo = 50000;
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        setor = new javax.swing.JButton();
        tarik = new javax.swing.JButton();
        petunjuk = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        informasi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Home"));
        jPanel1.setLayout(null);

        setor.setBackground(new java.awt.Color(51, 255, 204));
        setor.setText("Penyetoran");
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        jPanel1.add(setor);
        setor.setBounds(60, 80, 220, 23);

        tarik.setBackground(new java.awt.Color(51, 255, 204));
        tarik.setText("Penarikan");
        tarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarikActionPerformed(evt);
            }
        });
        jPanel1.add(tarik);
        tarik.setBounds(60, 120, 220, 23);

        petunjuk.setBackground(new java.awt.Color(51, 255, 204));
        petunjuk.setText("Petunjuk");
        petunjuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petunjukActionPerformed(evt);
            }
        });
        jPanel1.add(petunjuk);
        petunjuk.setBounds(60, 160, 220, 23);

        keluar.setBackground(new java.awt.Color(0, 255, 204));
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(60, 200, 220, 23);

        informasi.setBackground(new java.awt.Color(0, 255, 204));
        informasi.setText("Informasi Saldo");
        informasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informasiActionPerformed(evt);
            }
        });
        jPanel1.add(informasi);
        informasi.setBounds(60, 40, 220, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 110, 320, 250);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BANK RAKYAT SEMESTA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 50, 240, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 390);

        setBounds(0, 0, 424, 426);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void informasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informasiActionPerformed
        int z;
        
        javax.swing.JOptionPane.showMessageDialog(null, "Saldo Anda saat ini "
                        + "sebesar : " + saldo);
        z=javax.swing.JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BANK RAKYAT SEMESTA", 
                javax.swing.JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain 
                if (z==0) { 
                    new Home().setVisible(true);
                } else {
                javax.swing.JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BANK RAKYAT SEMESTA,"
                        + " ambil kartu ATM Anda."); 
                this.dispose();
                }
                this.dispose();
    }//GEN-LAST:event_informasiActionPerformed

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        String str;
        int s,z;
        
        str = javax.swing.JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran : " ); //menabung 
        s = Integer.parseInt(str); setor hasil = new setor(); 
        hasil.menabung(saldo, s); 
        saldo =hasil.getsaldo();
        javax.swing.JOptionPane.showMessageDialog(null, "Saldo Anda saat ini : " + saldo);
        z = javax.swing.JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BANK RAKYAT SEMESTA", 
                javax.swing.JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain 
                if (z==0) { 
                    new Home().setVisible(true);
                } else {
                javax.swing.JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BANK RAKYAT SEMESTA,"
                        + " ambil kartu ATM Anda."); 
                this.dispose();
                }
                this.dispose();
    }//GEN-LAST:event_setorActionPerformed

    private void tarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarikActionPerformed
        String trk;
        int t,z;
        
        trk = javax.swing.JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //menabung 
        t = Integer.parseInt(trk); 
        tarik mengambil = new tarik(); 
        mengambil.ambil(saldo,t); 
        saldo = mengambil.getsaldo();
        javax.swing.JOptionPane.showMessageDialog(null, "Saldo Anda saat ini : " + saldo);
        z=javax.swing.JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BANK RAKYAT SEMESTA", 
                javax.swing.JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain 
                if (z==0) { 
                    new Home().setVisible(true);
                } else {
                javax.swing.JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BANK RAKYAT SEMESTA,"
                        + " ambil kartu ATM Anda."); 
                this.dispose();
                }
                this.dispose();
    }//GEN-LAST:event_tarikActionPerformed

    private void petunjukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petunjukActionPerformed
        int z;
        
        javax.swing.JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi\n[1] Masukkan PIN dengan benar\n[2]"
                            + " Bertransaksilah dengan benar sesuai pilihan\n[3] Gunakan Uang sesuai kebutuhan"
                            + " dan rajinlah menabung\n ","INFO",1);
        z=javax.swing.JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BANK RAKYAT SEMESTA", 
                javax.swing.JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain 
                if (z==0) { 
                    new Home().setVisible(true);
                } else {
                javax.swing.JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BANK RAKYAT SEMESTA,"
                        + " ambil kartu ATM Anda."); 
                this.dispose();
                }
        this.dispose();
    }//GEN-LAST:event_petunjukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton informasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton keluar;
    private javax.swing.JButton petunjuk;
    private javax.swing.JButton setor;
    private javax.swing.JButton tarik;
    // End of variables declaration//GEN-END:variables
}
